"""changed sellername

Revision ID: 12a06584150a
Revises: 
Create Date: 2022-09-20 12:43:37.110345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12a06584150a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auction', 'sellerName')
    op.drop_column('auction', 'cropName')
    op.drop_column('current_auction', 'sellerName')
    op.drop_column('current_auction', 'cropName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current_auction', sa.Column('cropName', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('current_auction', sa.Column('sellerName', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('auction', sa.Column('cropName', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('auction', sa.Column('sellerName', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
