"""added crops and auction

Revision ID: 170acf54d164
Revises: 7d27b2dc407f
Create Date: 2022-07-23 01:10:42.629049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170acf54d164'
down_revision = '7d27b2dc407f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('cropId', sa.Integer(), nullable=False),
    sa.Column('variety', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('cropId')
    )
    op.create_table('auction',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('sellerId', sa.Integer(), nullable=True),
    sa.Column('cropId', sa.Integer(), nullable=True),
    sa.Column('minPrice', sa.Integer(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cropId'], ['crops.cropId'], ),
    sa.ForeignKeyConstraint(['sellerId'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auction')
    op.drop_table('crops')
    # ### end Alembic commands ###
