"""empty message

Revision ID: a0812d5e5767
Revises: d245babf8094
Create Date: 2022-07-24 06:44:11.432321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0812d5e5767'
down_revision = 'd245babf8094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_auction_datetime'), 'auction', ['datetime'], unique=False)
    op.drop_column('auction', 'date')
    op.drop_column('auction', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction', sa.Column('time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('auction', sa.Column('date', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_auction_datetime'), table_name='auction')
    op.drop_column('auction', 'datetime')
    # ### end Alembic commands ###
