"""added timer

Revision ID: b916a8b86156
Revises: fddbb42d1006
Create Date: 2022-07-23 21:18:58.566673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b916a8b86156'
down_revision = 'fddbb42d1006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timer', sa.Column('timerSeconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timer', 'timerSeconds')
    # ### end Alembic commands ###
