"""changed amount

Revision ID: c1937062e85b
Revises: 12a06584150a
Create Date: 2022-09-20 13:10:17.033028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1937062e85b'
down_revision = '12a06584150a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction', sa.Column('amount', sa.String(length=50), nullable=True))
    op.add_column('current_auction', sa.Column('amount', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('current_auction', 'amount')
    op.drop_column('auction', 'amount')
    # ### end Alembic commands ###
