"""empty message

Revision ID: c3217ada1a34
Revises: a0812d5e5767
Create Date: 2022-07-25 13:30:47.196662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3217ada1a34'
down_revision = 'a0812d5e5767'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction', sa.Column('variety', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auction', 'variety')
    # ### end Alembic commands ###
