"""added timer

Revision ID: d245babf8094
Revises: b916a8b86156
Create Date: 2022-07-23 21:19:31.999136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd245babf8094'
down_revision = 'b916a8b86156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timer', sa.Column('timerSecondsCount', sa.Integer(), nullable=True))
    op.drop_column('timer', 'timerSeconds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timer', sa.Column('timerSeconds', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('timer', 'timerSecondsCount')
    # ### end Alembic commands ###
