"""tep table

Revision ID: e28f8b7eb4e9
Revises: fc319c9c1823
Create Date: 2022-07-25 16:24:28.587297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e28f8b7eb4e9'
down_revision = 'fc319c9c1823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_auction',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('sellerName', sa.String(length=50), nullable=True),
    sa.Column('cropName', sa.String(length=50), nullable=True),
    sa.Column('sellerId', sa.Integer(), nullable=True),
    sa.Column('cropId', sa.Integer(), nullable=True),
    sa.Column('variety', sa.String(length=50), nullable=True),
    sa.Column('minPrice', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cropId'], ['crops.cropId'], ),
    sa.ForeignKeyConstraint(['sellerId'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_index(op.f('ix_current_auction_datetime'), 'current_auction', ['datetime'], unique=False)
    op.drop_table('timer')
    op.alter_column('auction', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auction', 'datetime',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.create_table('timer',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('timerSecondsCount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_current_auction_datetime'), table_name='current_auction')
    op.drop_table('current_auction')
    # ### end Alembic commands ###
