"""empty message

Revision ID: 67cbe96f7d59
Revises: b7162b5d4d3b
Create Date: 2022-07-26 12:41:23.548039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67cbe96f7d59'
down_revision = 'b7162b5d4d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('sellerId', sa.Integer(), nullable=True),
    sa.Column('buyerId', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_index(op.f('ix_ledger_datetime'), 'ledger', ['datetime'], unique=False)
    op.create_table('temp_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.Column('userBid', sa.Integer(), nullable=True),
    sa.Column('buyerid', sa.Integer(), nullable=True),
    sa.Column('buyerName', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auction',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('sellerName', sa.String(length=50), nullable=True),
    sa.Column('cropName', sa.String(length=50), nullable=True),
    sa.Column('sellerId', sa.Integer(), nullable=True),
    sa.Column('cropId', sa.Integer(), nullable=True),
    sa.Column('variety', sa.String(length=50), nullable=True),
    sa.Column('minPrice', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('currentBid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cropId'], ['crops.cropId'], ),
    sa.ForeignKeyConstraint(['sellerId'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_index(op.f('ix_auction_datetime'), 'auction', ['datetime'], unique=False)
    op.create_table('current_auction',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('sellerName', sa.String(length=50), nullable=True),
    sa.Column('cropName', sa.String(length=50), nullable=True),
    sa.Column('sellerId', sa.Integer(), nullable=True),
    sa.Column('cropId', sa.Integer(), nullable=True),
    sa.Column('variety', sa.String(length=50), nullable=True),
    sa.Column('minPrice', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('currentBid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cropId'], ['crops.cropId'], ),
    sa.ForeignKeyConstraint(['sellerId'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_index(op.f('ix_current_auction_datetime'), 'current_auction', ['datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_current_auction_datetime'), table_name='current_auction')
    op.drop_table('current_auction')
    op.drop_index(op.f('ix_auction_datetime'), table_name='auction')
    op.drop_table('auction')
    op.drop_table('temp_table')
    op.drop_index(op.f('ix_ledger_datetime'), table_name='ledger')
    op.drop_table('ledger')
    # ### end Alembic commands ###
