"""empty message

Revision ID: bb2df01d9bb6
Revises: d05787399de0
Create Date: 2022-07-25 22:52:20.175384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2df01d9bb6'
down_revision = 'd05787399de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('sellerName', sa.String(length=50), nullable=True),
    sa.Column('cropName', sa.String(length=50), nullable=True),
    sa.Column('sellerId', sa.Integer(), nullable=True),
    sa.Column('cropId', sa.Integer(), nullable=True),
    sa.Column('variety', sa.String(length=50), nullable=True),
    sa.Column('minPrice', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cropId'], ['crops.cropId'], ),
    sa.ForeignKeyConstraint(['sellerId'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_index(op.f('ix_auction_datetime'), 'auction', ['datetime'], unique=False)
    op.create_table('current_auction',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('sellerName', sa.String(length=50), nullable=True),
    sa.Column('cropName', sa.String(length=50), nullable=True),
    sa.Column('sellerId', sa.Integer(), nullable=True),
    sa.Column('cropId', sa.Integer(), nullable=True),
    sa.Column('variety', sa.String(length=50), nullable=True),
    sa.Column('minPrice', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cropId'], ['crops.cropId'], ),
    sa.ForeignKeyConstraint(['sellerId'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_index(op.f('ix_current_auction_datetime'), 'current_auction', ['datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_current_auction_datetime'), table_name='current_auction')
    op.drop_table('current_auction')
    op.drop_index(op.f('ix_auction_datetime'), table_name='auction')
    op.drop_table('auction')
    # ### end Alembic commands ###
