"""added cropName in auction table

Revision ID: e7a102348401
Revises: c3217ada1a34
Create Date: 2022-07-25 13:37:18.118480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a102348401'
down_revision = 'c3217ada1a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction', sa.Column('cropName', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auction', 'cropName')
    # ### end Alembic commands ###
