"""empty message

Revision ID: fc319c9c1823
Revises: e7a102348401
Create Date: 2022-07-25 14:37:08.381469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc319c9c1823'
down_revision = 'e7a102348401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction', sa.Column('sellerName', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auction', 'sellerName')
    # ### end Alembic commands ###
